/**
 * Scheduler manifest emitter — generates the artifacts a recurring cost-reduction
 * agent needs to run on a schedule.
 *
 * Three output surfaces:
 *   1. policy.yaml    — declarative policy the CLI tick consumes.
 *   2. Scheduler manifest — CronJob YAML | GHA workflow | crontab line+script.
 *   3. (optional) Initial dry-run CSV — what would change on the first tick.
 *
 * No network calls. Pure string emitters, fully unit-testable.
 */

// ─── shared types ─────────────────────────────────────────────────────────────

export type SchedulePreset =
  | 'daily-03utc'
  | 'every-6h'
  | 'every-12h'
  | 'every-24h-localtz'
  | string; // custom cron expression, e.g. "0 5 * * 1"

export type SchedulerKind = 'k8s_cron' | 'github_actions' | 'crontab' | 'eventbridge';

export interface PolicyOptions {
  /** List of service names the policy targets. Empty = all services. */
  target_services: string[];
  /** Desired savings percentage (1-95). */
  target_percent: number;
  /** Cron schedule. Either a preset name or a raw cron expression. */
  schedule: SchedulePreset;
  /** Which scheduler runtime to emit a manifest for. */
  scheduler: SchedulerKind;
  /** Path or URL to the customer gitops config repo. */
  config_plane: string;
  /** Services that must never be touched regardless of the policy. */
  exceptions: string[];
  /**
   * Minimum savings delta (percentage points) required before a new CSV
   * is committed. Prevents churn on small week-to-week fluctuations.
   */
  min_delta_pp: number;
  /** Log10x env ID — used to scope the metric queries. */
  env_id?: string;
  /** Kubernetes namespace for the CronJob (k8s_cron only). */
  namespace?: string;
  /** Name of the k8s Secret holding LOG10X_API_KEY (k8s_cron only). */
  secret_name?: string;
}

// ─── cron expression resolver ─────────────────────────────────────────────────

/**
 * Resolve a schedule preset to a canonical cron expression (5-field,
 * UTC). Custom strings are returned as-is — validation of arbitrary
 * expressions is left to the scheduler runtime.
 */
export function resolveCronExpression(schedule: SchedulePreset): string {
  switch (schedule) {
    case 'daily-03utc':      return '0 3 * * *';
    case 'every-6h':         return '0 */6 * * *';
    case 'every-12h':        return '0 */12 * * *';
    case 'every-24h-localtz': return '0 3 * * *'; // closest UTC proxy; note in comment
    default:                 return schedule;
  }
}

/**
 * Convert a 5-field cron expression to the EventBridge Scheduler form:
 * `cron(minutes hours day-of-month month day-of-week year)`.
 *
 * Scheduler rejects `*` in both day-of-month and day-of-week — exactly one
 * must be `?`. Day-of-week is turned into `?` when both are wildcards
 * (the common case for our presets).
 */
export function toAwsCronExpression(cron5: string): string {
  const fields = cron5.trim().split(/\s+/);
  if (fields.length !== 5) return `cron(${cron5} *)`;
  let [min, hour, dom, mon, dow] = fields;
  if (dow === '*') {
    dow = '?';
  } else if (dom === '*') {
    dom = '?';
  }
  return `cron(${min} ${hour} ${dom} ${mon} ${dow} *)`;
}

/** Parse `s3://bucket/prefix` into its parts; null when not an S3 URI. */
export function parseS3ConfigPlane(repo: string): { bucket: string; prefix: string } | null {
  if (!repo.startsWith('s3://')) return null;
  const rest = repo.slice('s3://'.length).replace(/\/+$/, '');
  const slash = rest.indexOf('/');
  if (slash < 0) return rest.length > 0 ? { bucket: rest, prefix: '' } : null;
  const bucket = rest.slice(0, slash);
  if (bucket.length === 0) return null;
  return { bucket, prefix: rest.slice(slash + 1) };
}

// ─── policy.yaml ──────────────────────────────────────────────────────────────

/**
 * Emit the `policy.yaml` file the recurring CLI consumes each tick.
 *
 * Format is deliberately simple YAML — no anchors, no multi-document
 * streams. A future CLI flag `--policy policy.yaml` loads this file.
 */
export function emitPolicyYaml(opts: PolicyOptions): string {
  const cronExpr = resolveCronExpression(opts.schedule);
  const targetServicesYaml =
    opts.target_services.length === 0
      ? '  # empty = all services\n  target_services: []\n'
      : `  target_services:\n${opts.target_services.map((s) => `    - ${yamlString(s)}`).join('\n')}\n`;
  const exceptionsYaml =
    opts.exceptions.length === 0
      ? '  exceptions: []\n'
      : `  exceptions:\n${opts.exceptions.map((s) => `    - ${yamlString(s)}`).join('\n')}\n`;

  const lines: string[] = [
    `# Log10x recurring cost-reduction policy`,
    `# Generated by log10x_setup_recurring — edit and re-commit as needed.`,
    `# The CLI reads this file at the start of each tick.`,
    `schema_version: "1.0"`,
    ``,
    `reduction:`,
    targetServicesYaml.trimEnd(),
    `  target_percent: ${opts.target_percent}`,
    exceptionsYaml.trimEnd(),
    `  min_delta_pp: ${opts.min_delta_pp}`,
    ``,
    `schedule:`,
    `  preset: ${yamlString(opts.schedule)}`,
    `  cron_utc: ${yamlString(cronExpr)}`,
    `  scheduler: ${yamlString(opts.scheduler)}`,
    ``,
    `config_plane:`,
    `  repo: ${yamlString(opts.config_plane)}`,
    ...(opts.env_id ? [`  env_id: ${yamlString(opts.env_id)}`] : []),
    ``,
  ];
  return lines.join('\n') + '\n';
}

// ─── k8s CronJob ──────────────────────────────────────────────────────────────

/**
 * Emit a Kubernetes CronJob manifest. Mounts a Secret for the API key
 * and runs `npx log10x-mcp --tick --policy /config/policy.yaml` on the
 * configured schedule.
 *
 * The ConfigMap for `policy.yaml` is emitted as a separate YAML document
 * (separated by `---`) so the user can `kubectl apply -f` the single file.
 */
export function emitK8sCronJob(opts: PolicyOptions): string {
  const cronExpr = resolveCronExpression(opts.schedule);
  const namespace = opts.namespace ?? 'log10x';
  const secretName = opts.secret_name ?? 'log10x-secret';
  const policyYaml = emitPolicyYaml(opts);
  // Base64-encode the policy YAML for the ConfigMap data field.
  const policyB64 = Buffer.from(policyYaml).toString('base64');

  return [
    `# Log10x recurring cost-reduction — Kubernetes CronJob`,
    `# Generated by log10x_setup_recurring.`,
    `# Apply with: kubectl apply -f log10x-recurring.yaml`,
    `---`,
    `apiVersion: v1`,
    `kind: ConfigMap`,
    `metadata:`,
    `  name: log10x-policy`,
    `  namespace: ${namespace}`,
    `data:`,
    `  policy.yaml: |`,
    ...policyYaml.split('\n').map((l) => `    ${l}`),
    `---`,
    `apiVersion: batch/v1`,
    `kind: CronJob`,
    `metadata:`,
    `  name: log10x-recurring`,
    `  namespace: ${namespace}`,
    `  labels:`,
    `    app: log10x-recurring`,
    `spec:`,
    `  schedule: ${yamlString(cronExpr)}`,
    `  concurrencyPolicy: Forbid`,
    `  successfulJobsHistoryLimit: 3`,
    `  failedJobsHistoryLimit: 3`,
    `  jobTemplate:`,
    `    spec:`,
    `      template:`,
    `        spec:`,
    `          restartPolicy: OnFailure`,
    `          containers:`,
    `            - name: log10x-tick`,
    `              image: node:22-alpine`,
    `              command: ["sh", "-c"]`,
    `              args:`,
    `                - |`,
    `                  npx --yes --package=log10x-mcp@latest tenx-recur --policy /config/policy.yaml`,
    `              env:`,
    `                - name: LOG10X_API_KEY`,
    `                  valueFrom:`,
    `                    secretKeyRef:`,
    `                      name: ${secretName}`,
    `                      key: LOG10X_API_KEY`,
    ...(opts.env_id
      ? [
          `                - name: LOG10X_ENV_ID`,
          `                  value: ${yamlString(opts.env_id)}`,
        ]
      : []),
    `                - name: LOG10X_GITOPS_REPO`,
    `                  value: ${yamlString(opts.config_plane)}`,
    `              volumeMounts:`,
    `                - name: policy`,
    `                  mountPath: /config`,
    `          volumes:`,
    `            - name: policy`,
    `              configMap:`,
    `                name: log10x-policy`,
    ``,
  ].join('\n');
}

// ─── GitHub Actions workflow ───────────────────────────────────────────────────

/**
 * Emit a GitHub Actions workflow YAML that runs `npx log10x-mcp --tick`
 * on the configured schedule.
 *
 * The workflow reads `LOG10X_API_KEY` from repository secrets and checks
 * out the gitops repo before running the tick so the CLI can read and
 * write the cap CSV files in-place.
 */
export function emitGitHubActions(opts: PolicyOptions): string {
  const cronExpr = resolveCronExpression(opts.schedule);
  // GitHub Actions cron runs in UTC. Append a comment for schedules where
  // the preset name implies timezone awareness.
  const scheduleComment =
    opts.schedule === 'every-24h-localtz'
      ? '  # Note: GitHub Actions cron runs in UTC. Adjust if you need local-TZ alignment.'
      : '';

  return [
    `# Log10x recurring cost-reduction — GitHub Actions workflow`,
    `# Generated by log10x_setup_recurring.`,
    `# Commit this file to .github/workflows/log10x-recurring.yml`,
    `name: log10x-recurring`,
    ``,
    `on:`,
    `  schedule:`,
    `    - cron: ${yamlString(cronExpr)}`,
    ...(scheduleComment ? [scheduleComment] : []),
    `  workflow_dispatch: {}  # manual trigger`,
    ``,
    `jobs:`,
    `  tick:`,
    `    runs-on: ubuntu-latest`,
    `    permissions:`,
    `      contents: write   # needed to commit updated cap CSV`,
    `      pull-requests: write`,
    `    steps:`,
    `      - name: Checkout gitops repo`,
    `        uses: actions/checkout@v4`,
    `        with:`,
    `          token: \${{ secrets.GITHUB_TOKEN }}`,
    ``,
    `      - name: Set up Node.js`,
    `        uses: actions/setup-node@v4`,
    `        with:`,
    `          node-version: "22"`,
    ``,
    `      - name: Run log10x tick`,
    `        env:`,
    `          LOG10X_API_KEY: \${{ secrets.LOG10X_API_KEY }}`,
    ...(opts.env_id ? [`          LOG10X_ENV_ID: ${opts.env_id}`] : []),
    `          LOG10X_GITOPS_REPO: ${opts.config_plane}`,
    `        run: |`,
    `          npx --yes --package=log10x-mcp@latest tenx-recur --policy policy.yaml`,
    ``,
  ].join('\n');
}

// ─── crontab ──────────────────────────────────────────────────────────────────

/**
 * Emit a crontab entry and a companion wrapper script.
 *
 * Returns an object with two string fields:
 *   `crontab_line` — one crontab line to add via `crontab -e`
 *   `wrapper_script` — a shell script the crontab entry invokes
 *
 * The wrapper script exports env vars and runs the tick, appending to a
 * local log file so the user can see the last run's output.
 */
export function emitCrontab(opts: PolicyOptions): { crontab_line: string; wrapper_script: string } {
  const cronExpr = resolveCronExpression(opts.schedule);
  const wrapperPath = '/usr/local/bin/log10x-tick.sh';

  const crontab_line = [
    `# Log10x recurring cost-reduction tick`,
    `${cronExpr} ${wrapperPath} >> /var/log/log10x-tick.log 2>&1`,
  ].join('\n');

  const wrapper_script = [
    `#!/usr/bin/env bash`,
    `# Log10x recurring cost-reduction wrapper`,
    `# Generated by log10x_setup_recurring.`,
    `# Install: sudo cp this-file.sh ${wrapperPath} && sudo chmod +x ${wrapperPath}`,
    `set -euo pipefail`,
    ``,
    `export LOG10X_API_KEY="\${LOG10X_API_KEY:-}"  # set in your environment or replace here`,
    ...(opts.env_id ? [`export LOG10X_ENV_ID="${opts.env_id}"`] : []),
    `export LOG10X_GITOPS_REPO="${opts.config_plane}"`,
    ``,
    `echo "[$(date -u '+%Y-%m-%dT%H:%M:%SZ')] log10x tick starting"`,
    `npx --yes --package=log10x-mcp@latest tenx-recur --policy "${opts.config_plane}/policy.yaml"`,
    `echo "[$(date -u '+%Y-%m-%dT%H:%M:%SZ')] log10x tick done"`,
    ``,
  ].join('\n');

  return { crontab_line, wrapper_script };
}

// ─── EventBridge Scheduler + CodeBuild (AWS-native, no cluster, no GitHub) ────

/**
 * Emit a CloudFormation template that runs the tick entirely inside the
 * customer's AWS account: an EventBridge Scheduler schedule starts a
 * CodeBuild build on each tick, and the build runs `tenx-recur` against an
 * S3 config plane.
 *
 * CodeBuild rather than Lambda or Fargate because the tick is a Node CLI
 * fetched with npx: CodeBuild provides a managed Node container with the
 * aws CLI present and needs no VPC, cluster, image publish, or bundling.
 *
 * The config plane is an S3 prefix (`s3://bucket/prefix`). The build pulls
 * `policy.yaml` from it and `tenx-recur` reads and writes its state files
 * under the same prefix. The engine-facing mute file lands at
 * `<prefix>/pipelines/run/receive/rate/mutes.csv` — point
 * `TENX_RECEIVE_MUTE_S3_URI` at that key.
 */
export function emitEventBridge(opts: PolicyOptions): string {
  const cronExpr = resolveCronExpression(opts.schedule);
  const awsCron = toAwsCronExpression(cronExpr);
  const plane = parseS3ConfigPlane(opts.config_plane);
  const bucket = plane?.bucket ?? 'YOUR-CONFIG-BUCKET';
  const prefix = plane ? (plane.prefix.length > 0 ? `${plane.prefix}/` : '') : 'log10x-config/';
  const planeUri = plane ? opts.config_plane.replace(/\/+$/, '') : 's3://YOUR-CONFIG-BUCKET/log10x-config';

  return [
    `# Log10x recurring cost-reduction — EventBridge Scheduler + CodeBuild tick`,
    `# Generated by log10x_setup_recurring.`,
    `# Deploy with:`,
    `#   aws cloudformation deploy --template-file log10x-recurring-cfn.yaml \\`,
    `#     --stack-name log10x-recurring --capabilities CAPABILITY_IAM \\`,
    `#     --parameter-overrides Log10xApiKeySecretArn=<secret-arn>`,
    `AWSTemplateFormatVersion: "2010-09-09"`,
    `Description: Log10x recurring tick — EventBridge Scheduler starts a CodeBuild run of tenx-recur.`,
    ``,
    `Parameters:`,
    `  Log10xApiKeySecretArn:`,
    `    Type: String`,
    `    Description: Secrets Manager secret ARN whose value is the LOG10X_API_KEY.`,
    ``,
    `Resources:`,
    `  TickLogGroup:`,
    `    Type: AWS::Logs::LogGroup`,
    `    Properties:`,
    `      LogGroupName: /aws/codebuild/log10x-recurring-tick`,
    `      RetentionInDays: 30`,
    ``,
    `  TickRole:`,
    `    Type: AWS::IAM::Role`,
    `    Properties:`,
    `      AssumeRolePolicyDocument:`,
    `        Version: "2012-10-17"`,
    `        Statement:`,
    `          - Effect: Allow`,
    `            Principal: { Service: codebuild.amazonaws.com }`,
    `            Action: sts:AssumeRole`,
    `      Policies:`,
    `        - PolicyName: log10x-tick`,
    `          PolicyDocument:`,
    `            Version: "2012-10-17"`,
    `            Statement:`,
    `              - Effect: Allow`,
    `                Action: [logs:CreateLogStream, logs:PutLogEvents]`,
    `                Resource: !GetAtt TickLogGroup.Arn`,
    `              - Effect: Allow`,
    `                Action: [s3:GetObject, s3:PutObject]`,
    `                Resource: arn:aws:s3:::${bucket}/${prefix}*`,
    `              - Effect: Allow`,
    `                Action: s3:ListBucket`,
    `                Resource: arn:aws:s3:::${bucket}`,
    `              - Effect: Allow`,
    `                Action: secretsmanager:GetSecretValue`,
    `                Resource: !Ref Log10xApiKeySecretArn`,
    ``,
    `  TickProject:`,
    `    Type: AWS::CodeBuild::Project`,
    `    Properties:`,
    `      Name: log10x-recurring-tick`,
    `      ServiceRole: !GetAtt TickRole.Arn`,
    `      TimeoutInMinutes: 15`,
    `      Artifacts: { Type: NO_ARTIFACTS }`,
    `      LogsConfig:`,
    `        CloudWatchLogs: { Status: ENABLED, GroupName: !Ref TickLogGroup }`,
    `      Environment:`,
    `        Type: LINUX_CONTAINER`,
    `        ComputeType: BUILD_GENERAL1_SMALL`,
    `        Image: aws/codebuild/amazonlinux-x86_64-standard:5.0`,
    `        EnvironmentVariables:`,
    `          - { Name: CONFIG_PLANE, Type: PLAINTEXT, Value: "${planeUri}" }`,
    `          - { Name: LOG10X_API_KEY, Type: SECRETS_MANAGER, Value: !Ref Log10xApiKeySecretArn }`,
    ...(opts.env_id
      ? [`          - { Name: LOG10X_ENV_ID, Type: PLAINTEXT, Value: ${yamlString(opts.env_id)} }`]
      : []),
    `      Source:`,
    `        Type: NO_SOURCE`,
    `        BuildSpec: |`,
    `          version: 0.2`,
    `          phases:`,
    `            install:`,
    `              runtime-versions:`,
    `                nodejs: 20`,
    `            build:`,
    `              commands:`,
    `                - aws s3 cp "$CONFIG_PLANE/policy.yaml" policy.yaml`,
    `                - npx --yes --package=log10x-mcp@latest tenx-recur --policy policy.yaml`,
    ``,
    `  SchedulerRole:`,
    `    Type: AWS::IAM::Role`,
    `    Properties:`,
    `      AssumeRolePolicyDocument:`,
    `        Version: "2012-10-17"`,
    `        Statement:`,
    `          - Effect: Allow`,
    `            Principal: { Service: scheduler.amazonaws.com }`,
    `            Action: sts:AssumeRole`,
    `      Policies:`,
    `        - PolicyName: start-tick`,
    `          PolicyDocument:`,
    `            Version: "2012-10-17"`,
    `            Statement:`,
    `              - Effect: Allow`,
    `                Action: codebuild:StartBuild`,
    `                Resource: !GetAtt TickProject.Arn`,
    ``,
    `  TickSchedule:`,
    `    Type: AWS::Scheduler::Schedule`,
    `    Properties:`,
    `      Name: log10x-recurring`,
    `      ScheduleExpression: ${yamlString(awsCron)}`,
    `      ScheduleExpressionTimezone: UTC`,
    `      FlexibleTimeWindow: { Mode: "OFF" }`,
    `      State: ENABLED`,
    `      Target:`,
    `        Arn: arn:aws:scheduler:::aws-sdk:codebuild:startBuild`,
    `        RoleArn: !GetAtt SchedulerRole.Arn`,
    `        Input: !Sub '{"ProjectName": "\${TickProject}"}'`,
    ``,
  ].join('\n');
}

// ─── YAML helpers ─────────────────────────────────────────────────────────────

/**
 * Minimal YAML scalar quoting: wrap in double-quotes if the string
 * contains characters that YAML parsers would mis-read as block/flow
 * indicators, or is a bare number/bool/null. Doesn't handle multi-line
 * strings (none of our outputs produce them).
 */
export function yamlString(s: string): string {
  // Already looks like a quoted string? Return as-is.
  if ((s.startsWith('"') && s.endsWith('"')) || (s.startsWith("'") && s.endsWith("'"))) {
    return s;
  }
  // Needs quoting if it contains special YAML characters or could be
  // misread as a non-string scalar.
  const needsQuote =
    /[:{}\[\],#&*?|<>=!%@`]/.test(s) ||
    /\s/.test(s) ||
    s === '' ||
    s === 'true' || s === 'false' || s === 'null' ||
    /^\d/.test(s);
  if (needsQuote) {
    return `"${s.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
  }
  return s;
}
